### ISSUE TITLE
X-Pack License not installing, only getting trial license

### ISSUE THREAD

**Issue by TJM** [elastic/puppet-elasticsearch#1026]
* Module version: 6.3.3
* Puppet version: 5.5.8
* OS and version: CentOS 7.6
* ES Version: 5.6.14

## Bug description
 
X-Pack License is not installing.

Here is the relevant puppet code:

```
  include elasticsearch
  include java

        elasticsearch::instance { $instance_name:
          ensure => present,
          config => $config_hash,
        }

```

Here is the relevant hieradata: (partially obfuscated)

```
elasticsearch::license:
  uid: 41bXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  type: platinum
  issue_date_in_millis: 1527724800000 # May 31, 2018
  expiry_date_in_millis: 1559865599999 # June 6, 2019
  max_nodes: 10
  issued_to: A Company
  issuer: Magdalena Kowalska
  signature: >
    (censored)
  start_date_in_millis: 1527724800000
```

I can see it in the catalog on the server /opt/puppetlabs/puppet/cache/client_data/catalog/$(hostname}.json

It is populated correctly, so I do not think that it is related to the hieradata or puppet code.

Here is  an excerpt of jq . (catalogfile):

```
    {
      "type": "Elasticsearch_license",
      "title": "xpack",
      "tags": [
        "elasticsearch_license",
        "xpack",
        "class",
        "elasticsearch::license",
        "elasticsearch",
        "license",
        "profile::elasticsearch",
        "profile",
        "role::elasticsearch",
        "role",
        "node",
        "default"
      ],
      "file": "/etc/puppetlabs/code/environments/des_qa/modules/elasticsearch/manifests/license.pp",
      "line": 90,
      "exported": false,
      "parameters": {
        "ensure": "present",
        "content": {
          "uid": "41bXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
          "type": "platinum",
          "issue_date_in_millis": 1527724800000,
          "expiry_date_in_millis": 1559865599999,
          "max_nodes": 10,
          "issued_to": "A Company",
          "issuer": "Magdalena Kowalska",
          "signature": "AAAAA(censored)\n",
          "start_date_in_millis": 1527724800000
        },
        "protocol": "https",
        "host": "sea1l2dcesa01.company.corp",
        "port": 9200,
        "timeout": 30,
        "username": "elastic",
        "password": "changeme",
        "ca_file": "/etc/pki/elastic/ca/ca.crt",
        "validate_tls": true,
        "provider": "xpack"
      }
    }
``` 

I have added some Puppet.debug statements into the xpack.rb in the only method (process_body) and it appears to show the trial license in there, so I am pretty sure it is getting the license.

As I have mentioned elsewhere, we are getting the following warning, but I do not think it is relevant either:

```
Warning: Found multiple default providers for elasticsearch_license: shield, xpack; using shield
```

Puppet debug output:

```
Debug: Executing: '/bin/systemctl is-active elasticsearch-es-01.service'
Debug: Executing: '/bin/systemctl is-enabled elasticsearch-es-01.service'
Debug: Connected to the ES instance in 0.000395336 seconds.
Debug: Prefetching xpack resources for elasticsearch_license
Debug: xpack - process_body - body: {
  "license" : {
    "status" : "active",
    "uid" : "9ec2d3c9-5e01-45b0-b4ef-8b3701281ec1",
    "type" : "trial",
    "issue_date" : "2019-03-18T23:55:03.415Z",
    "issue_date_in_millis" : 1552953303415,
    "expiry_date" : "2019-04-17T23:55:03.415Z",
    "expiry_date_in_millis" : 1555545303415,
    "max_nodes" : 1000,
    "issued_to" : "des_qa",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}

Debug: elastic_rest - results: [{:name=>"xpack", :ensure=>:present, :content=>{"license"=>{"status"=>"active", "uid"=>"9ec2d3c9-5e01-45b0-b4ef-8b3701281ec1", "type"=>"trial", "issue_date"=>"2019-03-18T23:55:03.415Z", "issue_date_in_millis"=>1552953303415, "expiry_date"=>"2019-04-17T23:55:03.415Z", "expiry_date_in_millis"=>1555545303415, "max_nodes"=>1000, "issued_to"=>"des_qa", "issuer"=>"elasticsearch", "start_date_in_millis"=>-1}}, :provider=>:xpack}]
```

I have to assume that something is breaking where it is comparing the values, but I have no idea where that is happening. Not really an expert on types/providers. :)

NOTE: We did previously add debug statements to print the URI and response in "rest" but did not see any attempt to POST the corrected license details.

Any assistance is appreciated.

**Comment by TJM** [comment]
The *only* thing I have noticed that is somewhat *out of place* would be the `\n` at the end of the signature. I used `eyaml encrypt -f` which got the newline at the end. However, I would think, that if there was an error comparing the values or installing the new license, I would see something about it.  (shrug)

**Comment by uberjew666** [comment]
I'm having the same issue.
The hash is correct and elasticsearch_license is reporting content changed however it doesn't actually apply. It will report change on every subsequent run.

```
Notice: /Stage[main]/Elasticsearch::License/Elasticsearch_license[xpack]/content: content changed {
  'license' => {
    'status' => 'active',
    'uid' => '038e1b29-50c3-4442-9cee-e7bdaad4b06d',
    'type' => 'basic',
    'issue_date' => '2019-11-06T11:33:07.213Z',
    'issue_date_in_millis' => 1573039987213,
    'max_nodes' => 1000,
    'issued_to' => 'strata_logs',
    'issuer' => 'elasticsearch',
    'start_date_in_millis' => -1
  }
} to {"license"=>{"uid"=>"0e18ca57-193d-45e7-a265-f0e5c3044a45", "type"=>"platinum", "issue_date_in_millis"=>1520294400000, "expiry_date_in_millis"=>1554076799999, "max_nodes"=>120, "issued_to"=>"some company", "issuer"=>"Magdalena Kowalska", "signature"=>"[redacted]", "start_date_in_millis"=>1520294400000}}
```

Here is the hash:
```
elasticsearch::license:
  license:
    uid: 0e18ca57-193d-45e7-a265-f0e5c3044a45
    type: platinum
    issue_date_in_millis: 1520294400000
    expiry_date_in_millis: 1554076799999
    max_nodes: 120,
    issued_to: 'some company'
    issuer: 'Magdalena Kowalska'
    signature: REDACTED
    start_date_in_millis: 1520294400000
```

I noticed the API endpoint in the provider was set to /_xpack/license. Since I'm using Elasticsearch 7.4, the documentation uses /_license instead. I've tried both and still receive the same issue.

**Comment by uberjew666** [comment]
@TJM I think your hash is incorrect, it should be:

```
elasticsearch::license:
  license:
    uid: 41bXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    type: platinum
    issue_date_in_millis: 1527724800000 # May 31, 2018
    expiry_date_in_millis: 1559865599999 # June 6, 2019
    max_nodes: 10
    issued_to: A Company
    issuer: Magdalena Kowalska
    signature: (censored)
    start_date_in_millis: 1527724800000
```
