### ISSUE TITLE
instance: ensure => absent creates dependency cycle

### ISSUE THREAD

**Issue by faxm0dem** [elastic/puppet-elasticsearch#173]
I just tried to exclude a node from the cluster by using the foilowing option in hiera:

``` YAML
elasticsearch::instance:
  loghost:
    ensure: absent
```

Apparently this results in a dependency cycle:

```
(File[/etc/elasticsearch/loghost] => Elasticsearch::Service[loghost] => Elasticsearch::Service::Init[loghost] => Service[loghost] => Elasticsearch::Service::Init[loghost] => Elasticsearch::Service[loghost] => Class[Elasticsearch::Config] => File[/etc/elasticsearch] => File[/etc/elasticsearch/loghost])
```
