### ISSUE TITLE
Shield integration

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#399]
Shield enables authentication for API calls.
Since we do a few of those with the puppet module we need to expose options to support that.

**Comment by cdenneen** [comment]
@electrical any update?

**Comment by electrical** [comment]
@cdenneen I'm afraid I left the company a few weeks ago and someone else is taking over.

**Comment by cdenneen** [comment]
@electrical thanks. 

Do we know who this will be? Anyway we can get even the basics of these modules for shield and kibana published and public contribution help to work on them?(even if not a published module right away) 
Problem right now with little insight into logstash 2.x support, beats, kibana, shield, etc people are left fending for themselves and hacking forks of these modules that majorly diverge or are creating their own because of the time lag on most of these. (For example I think the logstash module was getting the revamp after the 2.0 release of ES with all its goodness and multi instance support, think that was a year ago and we are on 2.2.x and soon 3.x)

Having these re-opened as public modules like the original electrical ones were might not be a bad idea if @elastic doesn't have the cycles to solely maintain?

**Comment by tylerjl** [comment]
Hi @cdenneen, sorry for the delayed response here. The short story here is that @jarpy and I will be helping to further the excellent work @electrical has already done. As a prerequisite to diving into the guts of the module, we'd really like to give the CI/testing environment some love to get it back up to speed running through the thorough test suite for some confidence moving forward.

Once that's done (and ideally in a place the community can access and interact with) we'll be in a great place to start actively accepting community PRs. The community work is *greatly* appreciated and if we can put some infrastructure in place to lower the barrier to entry with good testing infra, we can make community contributions happen more quickly and confidently.

I'll try and provide as much transparency as possible as we transition some things, please let us know about additional needs as well! :100:

**Comment by cdenneen** [comment]
@tylerjl thanks for the update 
I think as far as modules waiting for:
* shield 
* kibana
* logstash 2.x and up support 

(Put shield at top because figured would be quick win to get initial release out)

I left filebeats off this list for now because @pcfens has done great job of creating one and maintaining. So think besides the above list of missing modules the backlog of issues would b next of importance before filebeats module. 

Maybe creating a bullet list as issue to track order of what we can expect?

**Comment by tylerjl** [comment]
@cdenneen yep, that aligns pretty closely to the pulse I've gotten from others as well. Hopefully we can pick up the shield work efficiently to keep it moving.

I'm currently knee-deep in CI environment work, but hopefully we'll have a fully functioning CI pipeline Soon™.

**Comment by cdenneen** [comment]
@tylerjl Any luck in releasing the beta for puppet-shield plugin?

**Comment by tylerjl** [comment]
@cdenneen I'm happy to report I've been making lots of progress on Shield integration. I still need to put some work in on TLS management, but if anyone wants to offer feedback regarding design choices, please to check out the [branch diff](https://github.com/elastic/puppet-elasticsearch/compare/master...tylerjl:feature/shield-esusers) and let me know if the design pattern looks good from and end-user perspective. I'm first and foremost interested to know if this is usable for people.

I've gotten most of the CI shakiness sorted out, so Shield support is the primary focus right now.

**Comment by cdenneen** [comment]
@tylerjl awesome. Can you add realm support to that fork as well? 
(http://blog.comperiosearch.com/blog/2015/08/21/elasticsearch-security-shield/)

**Comment by tylerjl** [comment]
@cdenneen assuming you mean Active Directory realms, standing up a Windows test environments is obviously less straightforward than a Linux one. That said, I think at the very least managing the role mappings yaml file should be very doable now that I've written the native puppet provider for the yaml roles file. Again, I'm not sure what the most preferable way would be for people to define those mappings in puppet, so feel free to comment on the branch regarding how it's shaping up.

**Comment by cregev** [comment]
Any update when the PR is going to be merged ?

**Comment by tylerjl** [comment]
No ETA yet, but I'll be pushing updates regularly if anyone is anxious to watch progress.

**Comment by cdenneen** [comment]
@tylerjl sort of... the AD is just one option of a realm, you could use just about anything (LDAP, AD, OAuth, SAML, etc)... it's basically because of the custom realms (https://www.elastic.co/guide/en/shield/current/custom-realms.html) so esusers is just one realm... 
In your fork if you can define type the realm it could handle esusers for the basic use case but then just about any other provider anyone wants to use for shield authentication.

So for example most of my auth will be with esusers for applications but I would probably secure Kibana with shield and then use AD/LDAP to auth users to Kibana.

**Comment by fgimian** [comment]
Would love to see this too, so that we can easily manage local Shield users and LDAP configuration with Puppet :smile: 

For now, I'll write my own little module to manage these files.

Keep up the great work guys!
Fotis

**Comment by cdenneen** [comment]
@tylerjl I see the mapping support in your fork... I think once the realm support is added to the elasticsearch.yml.erb this should be working, right?

**Comment by tylerjl** [comment]
@cdenneen from what I understand, configuring realms is just a matter of defining the configuration in `elasticsearch.yml.erb`. If that's the case, you'd just need to set the `config =>` parameter in puppet as needed, so there isn't anything realm-specific the module needs (other than the mappings support.) Does that sound right? (this is helpful, I haven't done anything with AD in the past.)

**Comment by cdenneen** [comment]
Yeah I'm guessing custom config block would work and result should look something like this:

```yaml
shield.authc:
  realms:
    esusers:
      type: esusers
      order: 0
    ldap1:
      type: ldap
      order: 1
      enabled: false
      url: 'url_to_ldap1'
    ...
    ad1:
      type: active_directory
      order: 3
      url: 'url_to_ad'
```

Otherwise maybe an if condition and loop in the erb to do hiera lookup for all `shield::authc::realms` similar to https://github.com/jfryman/puppet-nginx/blob/master/templates/vhost/location_header.erb#L31-L45?

**Comment by tylerjl** [comment]
I'd prefer to avoid hiera lookups in the erb [per Puppet Lab's recommendation](https://docs.puppet.com/hiera/3.1/puppet.html#dont-use-the-lookup-functions-from-templates), but defining realm configuration in hiera should be as simple as something like the following in a hiera yaml config:

```yaml
---
elasticsearch::config:
  shield.authc:
    realms:
      esusers:
        type: users
...
```

The config on the `elasticsearch` class gets merged with instance configs so there's no need for hiera gymnastics to get a config into a defined instance in a manifest.

**Comment by cdenneen** [comment]
Understood... makes sense... so what's left before your fork gets merged? Documentation updates?

**Comment by tylerjl** [comment]
Just getting the tests clear, still some failures on different OS/puppet combinations... close, though!  😅

**Comment by tylerjl** [comment]
PR open at #624, do provide feedback if there are any parts that need changing.

**Comment by cdenneen** [comment]
@tylerjl using 0.11.0 and getting
```puppet
==> eslog: Error: Could not find a suitable provider for elasticsearch_shield_user_roles
```

**Comment by tylerjl** [comment]
@cdenneen those types of errors crop up when the requirements for a provider haven't been met - my guess is that it comes from [this line](https://github.com/elastic/puppet-elasticsearch/blob/0.11.0/lib/puppet/provider/elasticsearch_shield_user_roles/parsed.rb#L17) which checks for the existense of the `users_roles` file.

Is `/usr/share/elasticsearch/shield/users_roles` on the target system? (assuming this isn't OpenBSD)

**Comment by cdenneen** [comment]
@tylerjl no it doesn't exist there:

```
[vagrant@eslog ~]$ ls /usr/share/elasticsearch/shield/*
/usr/share/elasticsearch/shield/roles.yml  /usr/share/elasticsearch/shield/users
```
but does here:
```
[vagrant@eslog ~]$ ls /etc/elasticsearch/shield/
logging.yml  role_mapping.yml  roles.yml  roles.yml.new  users  users_roles
```

**Comment by cdenneen** [comment]
@tylerjl this is a fresh vagrant box (so cruft there). 
Is there something in config hash I need to add in order for this users_roles to be created under /usr/share/elasticsearch/shield? This is 2.3.3 centos rpm install from managed repo

**Comment by tylerjl** [comment]
So, my guess is that the `shield` directory exists there in `/etc` because the plugin was either installed 1) by hand or 2) by an earlier version of the module.

In version 0.11.0 of the module, any plugin installations should drop configuration files into `/usr/share/elasticsearch`, which helps to centralize the shield config files - earlier versions or running `plugin` by hand assumes your elasticsearch config lives under `/etc/elasticsearch`, which doesn't work with the puppet module's notion of instances, so the config files are centralized in `/usr/share` and recursively kept in sync with all instance directories (i.e., `/etc/elasticsearch/es-01/shield`.)

In your case you could either remove the module and then define it in puppet to manage, or, if you just want to start from scratch without any of the pre-packaged roles/other files, you could always create `users_roles` by hand.

It's a bit of an ugly workaround, but it's a compromise between respecting the security manager's need to only read config files within the CONF_DIR and keeping `/etc/elasticsearch` consistent with directories representing instance CONF_DIRs.

**Comment by bflad** [comment]
@tylerjl thanks for that last comment. In our environment we installed the shield plugin with an older version of this Puppet module and we needed to run this before running Puppet with the newer module: `cp -R /etc/elasticsearch/es-01/shield /usr/share/elasticsearch/`. Worked like a charm afterwards!

**Comment by cdenneen** [comment]
@bflad thanks, I haven't had time to test.
@tylerjl guess my concern here is you can't always assume that this will be on a fresh install so I would suggest there be some method of cleaning up old shield plugin prior to new plugin install so this works if it's added to already built system? Maybe one running 1.7.3 and 0.10.0 of the module.

**Comment by cdenneen** [comment]
@tylerjl There must still be a ordering issue here.
I rebuilt fresh box using 0.11.0 and it worked... made some modifications, destroyed my vagrant boxes, went to rebuild and got the same 
`==> eslogmd: Error: Could not find a suitable provider for elasticsearch_shield_user_roles`

Here is the output of those directories as before:

```
[vagrant@eslogmd ~]$ ls -la /etc/elasticsearch/
total 12
drwxr-xr-x   3 elasticsearch elasticsearch   20 Jun  9 10:48 .
drwxr-xr-x. 84 root          root          8192 Jun  9 10:48 ..
drwxr-x---   2 root          elasticsearch    6 May 17 11:49 scripts

[vagrant@eslogmd ~]$ ls -la /usr/share/elasticsearch/shield/
total 0
drwxr-xr-x 2 root          root            6 Jun  9 10:48 .
drwxr-xr-x 8 elasticsearch elasticsearch 146 Jun  9 10:48 ..
```

Only large difference is I changed the default `elasticsearch::config` in hiera to be able to have per instance configs.

Here is all my data, in case it helps tell me where I made a stupid mistake ;-):

```yaml
---
profile::elasticsearch::es_instances:
  - 'es-01'
  - 'es-02'
profile::elasticsearch::data::config:
  cluster.name: 'loggingtest'
  node.name: "%{::hostname}"
  index.number_of_shards: 5
  index.number_of_replicas: 1
  bootstrap.mlockall: true
  discovery.zen.ping.unicast.hosts:
    - 'eslogmd'
    - 'eslogm'
  discovery.zen.ping.multicast.enabled: false
  node.data: true
  node.master: false
  http.port: '9200'
profile::elasticsearch::master::config:
  cluster.name: 'loggingtest'
  node.name: "%{::hostname}"
  index.number_of_shards: 5
  index.number_of_replicas: 1
  bootstrap.mlockall: true
  discovery.zen.ping.unicast.hosts:
    - 'eslogmd'
    - 'eslogm'
  discovery.zen.ping.multicast.enabled: false
  node.data: false
  node.master: true
  http.port: '9201'
elasticsearch::init_defaults:
  ES_HOME: '/usr/share/elasticsearch'
  MAX_OPEN_FILES: '65535'
  MAX_MAP_COUNT: '262144'
  LOG_DIR: '/var/log/elasticsearch'
  DATA_DIR: '/data/elasticsearch'
  WORK_DIR: '/tmp/elasticsearch'
  ES_USER: 'elasticsearch'
  ES_GROUP: 'elasticsearch'
  ES_JAVA_OPTS: '-Djava.net.preferIPv4Stack=true'
  ES_HEAP_SIZE: '128m'
  MAX_LOCKED_MEMORY: 'unlimited'
elasticsearch::java: true
elasticsearch::datadir: '/data/elasticsearch'
elasticsearch::status: 'enabled'
```

```puppet
class profile::elasticsearch(
  $es_instances = 'es-01'
) {
  class {'::elasticsearch':
    manage_repo   => true,
    repo_version  => '2.x',
    java_package  => 'java-1.8.0-openjdk-headless',
    package_pin   => true,
    version       => '2.3.3',
  }
  ::elasticsearch::plugin{'mobz/elasticsearch-head':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'lmenezes/elasticsearch-kopf':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'royrusso/elasticsearch-hq':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'license':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'shield':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'watcher':
    instances => $es_instances
  }
  ::elasticsearch::plugin{'marvel-agent':
    instances => $es_instances
  }
  elasticsearch::shield::user { 'admin':
    password => 'changeme',
    roles    => ['admin'],
  }
}
```

```puppet
class profile::elasticsearch::master(
  $config = {}
) {
  include ::profile::elasticsearch
  ::elasticsearch::instance {'es-02':
    config => $config
  }
  firewall { '101 ES MASTER HTTP':
    proto  => 'tcp',
    action => 'accept',
    dport  => ['9201','9301'],
  }
}
```

```puppet
class profile::elasticsearch::data(
  $config = {}
) {
  include ::profile::elasticsearch
  ::elasticsearch::instance {'es-01':
    config => $config
  }
  firewall { '100 ES HTTP':
    proto  => 'tcp',
    action => 'accept',
    dport  => ['9200','9300'],
  }
}
```
