### ISSUE TITLE
Plugin Install on centos 7 fails since version 0.9.6

### ISSUE THREAD

**Issue by schlitzered** [elastic/puppet-elasticsearch#423]
Hey,

i am running centos 7, with puppet 3.6.2 + hiera.

i have this in a manifest:

```
class profiles::elasticsearch {
  include '::elasticsearch'
  require '::profiles::java'

  $elinstances = hiera_hash('elasticsearch::instance', {})
  create_resources('elasticsearch::instance', $elinstances)

  $elplugin = hiera_hash('elasticsearch::plugin', {})
  create_resources('elasticsearch::plugin', $elplugin)
}
```

this in a hiera yaml file:

```
elasticsearch::instance:
  default:
    status: disabled
    config:
      node.name: dev_vm
      node.local: true
      http.enabled: true
    init_defaults:
      ES_HEAP_SIZE: 128m

elasticsearch::plugin:
  lmenezes/elasticsearch-kopf:
    module_dir: kopf
    instances: default
  elasticsearch/marvel/latest:
    module_dir: marvel
    instances: default
  elasticsearch/elasticsearch-cloud-aws/2.5.0:
    module_dir: cloud-aws
    instances: default
  jprante/elasticsearch-knapsack:
    module_dir: knapsack
    instances: default
    url: http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/1.5.1.0/elasticsearch-knapsack-1.5.1.0-plugin.zip
  
```

this is what happens if i run puppet apply:
```
[root@localhost ~]# export FACTER_ROLE=dev_vm; sudo -E puppet apply /etc/puppet/manifests/site.pp      
Notice: Compiled catalog for localhost.locallan in environment production in 3.52 seconds
Error: Could not set content on file: can't modify frozen String
```

as soon as i disable the plugins (comment them out in hiera), the manifests work fine.

i have checked all current version (0.9.8, 0.9.7, 0.9.6), there all have the same issue.

version 0.9.5 is working file.
