### ISSUE TITLE
Custom ES_MIN_MEM and ES_MAX_MEM values not propagating properly

### ISSUE THREAD

**Issue by bhuto** [elastic/puppet-elasticsearch#589]
I am testing this module using a CentOS 6 Vagrant box and in my hiera file I have the following code:
```
elasticsearch::instances:
  master:
    config: 
      node.name: "%{hostname}-master"
      node.master: true
      node.data: false
      http.port: 29200
      transport.tcp.port: 29300
      discovery.zen.ping.multicast.enabled: false
    init_defaults:
      'ES_MIN_MEM': '512m'
      'ES_MAX_MEM': '512m'
```
This leads to the following default file for the 'master' instance, as expected:
```
[vagrant@vagrant-centos-6 ~]$ cat /etc/sysconfig/elasticsearch-master
CONF_DIR=/etc/elasticsearch/master
CONF_FILE=/etc/elasticsearch/master/elasticsearch.yml
ES_GROUP=elasticsearch
ES_HOME=/usr/share/elasticsearch
ES_USER=elasticsearch
LOG_DIR=/var/log/elasticsearch/master
MAX_OPEN_FILES=65535
ES_MAX_MEM=512m
ES_MIN_MEM=512m
```
However, on starting the service using `sudo /etc/init.d/elasticsearch-master start`, it starts with the default  '256m' and '1g' values.
```
[vagrant@vagrant-centos-6 ~]$ ps aux| grep elasticsearch
497      19652 84.2  5.2 3139944 206844 ?      Sl   00:15   0:03 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.1.1.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -p /var/run/elasticsearch/elasticsearch-master.pid -d -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch/master -Des.default.path.data= -Des.default.path.work= -Des.default.path.conf=/etc/elasticsearch/master
vagrant  19669  0.0  0.0 103244   860 pts/0    S+   00:15   0:00 grep elasticsearch
```
My understanding is that this is because the script in /etc/init.d/ (created via the corresponding template file) does not export the ES_MIN_MEM and ES_MAX_MEM variables, like it does for some other variables like ES_HEAP_SIZE and ES_HEAP_NEWSIZE, after it calls the defaults script (https://github.com/elastic/puppet-elasticsearch/blob/master/templates/etc/init.d/elasticsearch.RedHat.erb#L38). This causes the `/user/share/elasticsearch/bin/elasticsearch.in.sh` script to infer that the variable is not set and it ends up using the default values. Making a change to the init file template by adding export directives for those two variables seems to make it work. Two questions then:

1. Is this a correct assessment and thus a bug?
2. Does the simple fix suggested above solve things or are there potential issues there?
