### ISSUE TITLE
Multinode cluster 

### ISSUE THREAD

**Issue by rameshmimit** [elastic/puppet-elasticsearch#631]
Seems like module lacking the setting up multinode cluster with different node names assigned to different instances on different servers.
Eg.

Server-1
Instance: es-01
nodename: hostname

Server-2
Instance: es-02
nodename: hostname

Current module does not have provision to assign instances names to different nodes. Below is my hiera yaml 

```
classes:
  - elasticsearch
  - wget

elasticsearch::manage_repo: true
elasticsearch::repo_version: '2.x'

## Elasticsearch Related Stuff
elasticsearch::version: '2.3.1-1'
elasticsearch::autoupgrade: false
elasticsearch::status: 'enabled'
elasticsearch::serviceprovider: 'init'
elasticsearch::datadir: '/data'

elasticsearch::config:
  cluster:
    name: 'Westeros'
  bootstrap:
    mlockall: true
  host:
    network: "%{::ipaddress}"
  index:
    number_of_shards: '1'
    number_of_replicas: '3'
    refresh_interval: '5'
    codec: 'best_compression'
elasticsearch::instances:
  BlueSky:
    config:
      node.name: 'BlueSky'
    init_defaults:
        ES_HEAP_SIZE: '12g'
        MAX_OPEN_FILES: 65535
        MAX_LOCKED_MEMORY: 'unlimited'
        MAX_MAP_COUNT: 262144
  RedFace:
    config:
      node.name: 'RedFace'
    init_defaults:
        ES_HEAP_SIZE: '12g'
        MAX_OPEN_FILES: 65535
        MAX_LOCKED_MEMORY: 'unlimited'
        MAX_MAP_COUNT: 262144
```

In any cluster one might want to keep all the java related settings same on similar spec nodes. It might be possible someone wont even care about which server has which node name. Right now i dont see any way to keep my java settings same on all the nodes and installing the same plugins on all the servers.
