### ISSUE TITLE
Perhaps offer the ability to manage the SSL cert for the Marvel agent exporter?

### ISSUE THREAD

**Issue by fgimian** [elastic/puppet-elasticsearch#640]
Hello there, unless I'm mistaken, this module doesn't offer the ability to create and manage the SSL keystore for you in relation to Marvel exporting:

i.e.

```yaml
marvel.agent.exporters:
  id1:                              # default local exporter
    type: local

  id2:                                     # example of an http exporter
    type: http                             # exporter type, local or http
    host: [ "http://domain:port",... ]     # host(s) to send data to over http or https

    auth:
      username: <string>            # basic auth username
      password: <string>            # basic auth password

    connection:
      timeout: <time_value>         # http connection timeout (default: 6s)
      read_timeout: <time_value>    # http response timeout (default: connection.timeout * 10)
      keep_alive: true | false      # use persistent connections (default: true)

    ssl:
      hostname_verification: true | false  # check host certificate (default: true)
      protocol: <string>                   # security protocol (default: TLSv1.2)
      truststore.path: /path/to/file       # absolute path to the truststore
      truststore.password: <string>        # password for the truststore
      truststore.algorithm: <string>       # format for the truststore (default: SunX509)
```

(from [Configuring Marvel](https://www.elastic.co/guide/en/marvel/current/configuration.html))

I guess it's tough to really cater for all these scenarios, but I assume that most commercial customers like us will be using Marvel.

What do you think? 😄 

Cheers
Fotis
