### ISSUE TITLE
Multi instance broken?

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#659]
@tylerjl Just curious, as I thought I had this working, but it seems that multiple instances isn't working on same server anymore.
When I start "service elasticsearch-master start" elasticsearch-data dies (and vice versa).
ES version is `2.3.3-1`
OS is `CentOS Linux release 7.2.1511 (Core)`
puppet module is `0.11.0`
puppet version is `4.3.2`

Here are my configs, it might be stupid mistake on my part but any red herrings?:

```yaml
### MANAGED BY PUPPET ###
---
bootstrap:
  mlockall: true
cluster:
  name: vagrant-logging
discovery:
  zen:
    ping:
      multicast:
        enabled: false
      unicast:
        hosts:
             - esmaster:9201
http:
  port: 9200
index:
  number_of_replicas: 1
  number_of_shards: 5
network:
  host: _enp0s8_
node:
  data: true
  master: false
  name: esmaster-data
path:
  data: /var/lib/elasticsearch/data
  logs: /var/log/elasticsearch/data
```
```yaml
### MANAGED BY PUPPET ###
---
bootstrap:
  mlockall: true
cluster:
  name: vagrant-logging
discovery:
  zen:
    ping:
      multicast:
        enabled: false
      unicast:
        hosts:
             - esmaster:9201
http:
  port: 9201
index:
  number_of_replicas: 1
  number_of_shards: 5
network:
  host: _enp0s8_
node:
  data: false
  master: true
  name: esmaster-master
path:
  data: /var/lib/elasticsearch/master
  logs: /var/log/elasticsearch/master
```

and the esmaster is in the local hosts file so it should route fine:

`127.0.1.1       esmaster.vm.local       esmaster`

Let me know if there is anything else I can provide.
