### ISSUE TITLE
Template module re-writes template every run

### ISSUE THREAD

**Issue by bmeekhof** [elastic/puppet-elasticsearch#678]
* Module version: 0.13.0
* Elasticsearch version: 2.3.5
* Puppet version: 3.8.7
* OS and version: RHEL 7

## Bug description

Module is re-writing identical elastic template every run even though no changes are required.  As you can see below there are slight differences in between what the module reads from elastic and what it then puts as update but the template settings are identical.   The puppet output below occurs every run even though the 'change' is successfully accepted by elasticsearch.  

I've verified the issue on all of our elasticsearch cluster nodes.  

Puppet output (linebreaks inserted for readability):
```
Notice: /Stage[main]/Logging::Elasticsearch/Elasticsearch::Template[default]/Elasticsearch_template[default]/content: 

content changed {'aliases' => {}, 'mappings' => {}, 'order' => '0', 
'settings' => {'index' => {'number_of_replicas' => '2', 'number_of_shards' => '1'}},  'template' => '*'} 

to '{"order"=>0, "aliases"=>{}, "template"=>"*", "settings"=>{"number_of_replicas"=>2, "number_of_shards"=>1}}'`
```

Manifest:

```
elasticsearch::template { 'default':
        content => '{"template":"*","settings":{"number_of_replicas":2, "number_of_shards":1}}'
  }
```

**Comment by tylerjl** [comment]
Thanks for the report - I actually stumbled across this yesterday and know what's happening; I'm working on a fix and will roll this into a bugfix release of the module. Sorry for the issues!  🐛 

Note that one issue I'm still trying to figure out is how to reconcile the fact that you can define settings as `"settings":{"number_of_replicas":2}` but the API returns settings in the form `"settings":{"index":{"number_of_replicas":2}}`, so I'm still trying to find a good way to bring those in sync without requiring everyone to change their template content.

**Comment by tylerjl** [comment]
@bmeekhof I've merged a fix in #679 that _should_ work. I tested your specific case to get the fix right, but if you get a chance, it would be helpful to know whether the change fixes your case in the field as well before calling this definitively fixed. Otherwise I'll just release this as part of the next bugfix release and assume things look good. 👍

**Comment by bmeekhof** [comment]
@tylerjl The fix resolves the issue for me, thanks!

**Comment by siliconalchemy** [comment]
Hi, I'm coming across the same issue trying to write a very simple template:
```
content changed {'aliases' => {}, 'mappings' => {}, 'order' => '0', 'settings' => {'index' => {'number_of_replicas' => '2', 'number_of_shards' => '1'}}, 'template' => 'logstash'} to '{"order"=>0, "aliases"=>{}, "mappings"=>{}, "template"=>"logstash", "index_patterns"=>["logstash*"], "settings"=>{"index"=>{"number_of_shards"=>1, "number_of_replicas"=>2}}}'
```
Using module version 0.15.0:
├── elasticsearch-elasticsearch (v0.15.0)

**Comment by tylerjl** [comment]
@siliconalchemy what is Elasticsearch returning when you fetch the existing template in the cluster? For example, `curl 'http://localhost:9200/_template/logstash?format=yaml'` just so we can see what's currently being stored.

The diff seems to indicate that `index_patterns` isn't seen in the existing template in comparison to what you're indicating it should have, so that's the disparity between the two.

**Comment by siliconalchemy** [comment]
```
---
logstash:
  order: 0
  version: 50001
  template: "logstash-*"
  settings:
    index:
      refresh_interval: "5s"
  mappings:
    _default_:
      dynamic_templates:
      - message_field:
          path_match: "message"
          mapping:
            norms: false
            type: "text"
          match_mapping_type: "string"
      - string_fields:
          mapping:
            norms: false
            type: "text"
            fields:
              keyword:
                type: "keyword"
          match_mapping_type: "string"
          match: "*"
      _all:
        norms: false
        enabled: true
      properties:
        '@timestamp':
          include_in_all: false
          type: "date"
        geoip:
          dynamic: true
          properties:
            ip:
              type: "ip"
            latitude:
              type: "half_float"
            location:
              type: "geo_point"
            longitude:
              type: "half_float"
        '@version':
          include_in_all: false
          type: "keyword"
  aliases: {}
```

OK so clearly this is clashing with some elasticsearch/logstash default template.  So if I rename it to logstash-custom, I get the same issue and here's the output:
```
# curl 'http://localhost:9200/_template/logstash-custom?format=yaml'
---
logstash-custom:
  order: 0
  template: "logstash-custom"
  settings:
    index:
      number_of_shards: "1"
      number_of_replicas: "2"
  mappings: {}
  aliases: {}
```
You're right, the index_patterns is missing.
