### ISSUE TITLE
Elasticsearch 5.x init script fails

### ISSUE THREAD

**Issue by cdino** [elastic/puppet-elasticsearch#748]
* Module version: 0.15.1
* Puppet version: 3.8
* OS and version: CentOS 6.8

## Bug description
after a fresh OS installation and puppet run on my test environment for ES 5.x the elasticsearch init script fails:
```
[root@ppsolees01 ~]# starts elasticsearch

Option                Description
------                -----------
-E <KeyValuePair>     Configure a setting
-V, --version         Prints elasticsearch version information and exits
-d, --daemonize       Starts Elasticsearch in the background
-h, --help            show help
-p, --pidfile <Path>  Creates a pid file in the specified path on start
-q, --quiet           Turns off standard ouput/error streams logging in console
-s, --silent          show minimal output
-v, --verbose         show verbose output
ERROR: Setting [default.path.conf] must not be empty
```
I'm using the same manifest as the production one.
This is the configuration generated by the module:
```yaml
### MANAGED BY PUPPET ###
---
action.disable_delete_all_indices: true
bootstrap.mlockall: true
cluster.name: ppsole
cluster.routing.allocation.awareness.attributes: machine
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts:
  - "ppsolees01:9300"
  - "ppsolees01:9301"
  - "ppsolees01:9302"
  - "ppsolees01:9303"
  - "ppsolees02:9300"
  - "ppsolees02:9301"
  - "ppsolees02:9302"
  - "ppsolees02:9303"
indices.store.throttle.max_bytes_per_sec: "150mb"
network.host: "x.x.x.x"
node.machine: ppsolees01
node.name: ppsolees01-ppes0
path.data: /usr/share/elasticsearch/data/ppes0
path.logs: /var/log/elasticsearch/ppes0
path.repo: /sysbackup/elasticsearch
```

seems that the init script is not able to get the variables `${CONF_DIR}` and  `${DATA_DIR}`
