### ISSUE TITLE
$logdir doesn't work via HIERA

### ISSUE THREAD

**Issue by smitjainsj** [elastic/puppet-elasticsearch#758]
I am trying to change **logdir** value for a instance defined in hiera but it doesn't change to a new path.

For eg: /var/log/elasticsearch --> /opt/elasticsearch/logs

```
## Hiera Config
elasticsearch::instances:
    'bb-es01':
        config:
            'node.name': 'elk-server.example.local'
            'node.data': true
            'node.master': true
            'network.host': '0.0.0.0'
            'datadir': [ '/opt/elasticsearch/data']
            'logdir': [ '/opt/elasticsearch' ]

```

Also, a big thanks for maintaining this module. Keep it up!!! 

* Module version: 0.15.1 
* Puppet version: 4.8
* OS and version: Ubuntu 14.04

**Comment by tylerjl** [comment]
@smitjainsj because the Puppet module manages the actual log directory to ensure it has the right permissions and ownership, you need to specify the directory at a higher level than the raw config file.

In your case, you can use something like the following:

```yaml
## Hiera Config
elasticsearch::instances:
    'bb-es01':
        logdir: /opt/elasticsearch/bb-es01
        config:
            'node.name': 'elk-server.example.local'
            'node.data': true
            'node.master': true
            'network.host': '0.0.0.0'
            'datadir': [ '/opt/elasticsearch/data']
```

Or, if you prefer to set the logging directory globally and let the module name it for your instance:

```yaml
## Hiera Config
elasticsearch::logdir: /opt/elasticsearch
elasticsearch::instances:
    'bb-es01':
        config:
            'node.name': 'elk-server.example.local'
            'node.data': true
            'node.master': true
            'network.host': '0.0.0.0'
            'datadir': [ '/opt/elasticsearch/data']
```

The module will set the configuration file setting appropriately. Let me know if this answers your question.
