### ISSUE TITLE
Template corruption

### ISSUE THREAD

**Issue by faxm0dem** [elastic/puppet-elasticsearch#779]
* Module version: 0.16.0
* Puppet version: 3.8
* OS and version: CentOS7

## Bug description

When pushing the following template: (notice the serialized part)

```YAML
elasticsearch:::templates:
  foo:
    content: |-
      {
        "order": 0,
        "template": "test-*",
        "settings": {
          "index.number_of_replicas": "1"
        }
      }
```

the following gets pushed to elasticsearch instead:

```JSON
{
  "order": 0,
  "aliases": {},
  "mappings": {},
  "template": "test-*",
  "settings": {
    "index": {
      "index.number_of_replicas": 1
    }
  }
}
```

Note the duplicated index key.
