### ISSUE TITLE
ES 6.0 deprecation: path.data CANNOT contain cluster name

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/puppet-elasticsearch#841]
* Module version: any
* Puppet version: any
* OS and version: any

## Feature Description

I stumbled upon this deprecation warning:

```
[2017-06-01T14:16:14,014][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/opt/elasticsearch/data/dev_something], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
```

Keeping in mind this breaking change will cost a lot for someone :cactus: ...
The module is adding the cluster name, probably to handle multiple installs on the same machine, which is a nice idea, but makes it incompatible with 6.0...

**Comment by tylerjl** [comment]
@lucabelluccini I tried to reproduce this a few different ways but couldn't get Elasticsearch to emit the types of logs you're seeing. The module doesn't interpolate the cluster name anywhere into the data path - by default on most linux systems, the module will define `path.data` as `/var/lib/elasticsearch/$instance` without the cluster in the path, just the instance name. Do you have an example manifest that causes the behavior?

**Comment by lucabelluccini** [comment]
Hello @tylerjl 
the culprit is the usage of the cluster name as instance name, but I didn't saw anything wrong doing so (and I do not understand why it should be forbidden).

I am using hiera, strongly relying on it.
Given the hierarchy
- role (elasticsearch)
- cluster (phase_project)
- fqdn (hostname.domain)

Here it is a sample of each

Role level: elasticsearch.yml
```
---
classes:
  - profile::elasticsearch

profile::limit::memlock::user: 'elasticsearch'
profile::limit::memlock::value: 'unlimited'
profile::limit::nproc::user: 'elasticsearch'
profile::limit::nproc::value: '50000'
profile::limit::nofile::user: 'elasticsearch'
profile::limit::nofile::value: '65536'
profile::sysctl::vm__max_map_count::value: '262144'

java::repository: 'http://ayumrepo/java'
java::version: '1.8.0_102-1'
java::package: 'oracle-jdk8'
java::symlink: {
  'source': '/usr/lib/jvm/java-1.8.0-oracle',
  'target': '/usr/lib/jvm/java-1.8.0-oracle-1.8.0_102.x86_64'
}

profile::elasticsearch::java_home: '/usr/lib/jvm/java-1.8.0-oracle'

elasticsearch::init_defaults:
  MAX_LOCKED_MEMORY: 'unlimited'
  MAX_OPEN_FILES: 65535
  MAX_MAP_COUNT: 262144
  JAVA_HOME: '/usr/lib/jvm/java-1.8.0-oracle'

profile::elasticsearch::ssl_files_path: /opt/elasticsearch/ssl
```

Cluster level: phase_project.yml
```
---
profile::elasticsearch::repository: 'http://ayumrepo/elastic-5.x/'

elasticsearch::version: '5.4.0'
elasticsearch::security_plugin: 'x-pack'

elasticsearch::config:
  cluster.name: "%{::cluster}"
  network.host: "%{::hostname}"
  http.enabled: True
  http.port: 9200
  transport.tcp.port: 9300
  bootstrap.memory_lock: True
  bootstrap.system_call_filter: False
  action.destructive_requires_name: true
  discovery.zen.minimum_master_nodes: 2
  discovery.zen.ping.unicast.hosts: ['hostname0.domain', 'hostname1.domain', 'hostname2.domain']
  xpack.monitoring.enabled: False
  xpack.security.enabled: True
  xpack.watcher.enabled: False
  xpack.graph.enabled: False
  xpack.ml.enabled: False
  xpack.security.audit.enabled: True
  xpack.security.audit.outputs: [ logfile ]
  xpack.security.audit.logfile.events.exclude: ['access_granted', 'authentication_success']
  xpack.security.dls_fls.enabled: True
  xpack.security.authc.accept_default_password: false
  xpack.security.authc.anonymous:
    username : anonuser
    roles : ['monitoring']
    authz_exception : true
  xpack.security.authc.realms:
  ...

elasticsearch::plugins:
  'x-pack':
    url: 'https://somewebserver/elasticsearch-5-plugin/x-pack-5.4.0.zip'

profile::elasticsearch::logdir: '/opt/elasticsearch/log'

```

Fqdn level: hostname0.domain
```
profile::elasticsearch::datalvm_lv_size: 50G
profile::elasticsearch::loglvm_lv_size: 150G

elasticsearch::jvm_options: ['-Xms1800M', '-Xmx1800M']
elasticsearch::instances:
  "%{::cluster}":
    config:
      node.name: "%{::hostname}"
      node:
        master: True
        data: False
        ingest: False
        ml: False
```
