### ISSUE TITLE
Support query and field_security in X-Pack security role definition

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/puppet-elasticsearch#854]
## Feature Description

Hello, I would suggest to enhance the role type to support query and field_security.
Ref. https://www.elastic.co/guide/en/x-pack/current/field-and-document-access-control.html

I am trying to revive the CLA to try to contribute on this.

**Comment by tylerjl** [comment]
Sounds good @lucabelluccini, I'll keep an eye open for any PRs. 👍

**Comment by lucabelluccini** [comment]
Hello,
I just tested the following hieradata (profile::elasticsearch::es_roles is just a hash used to instantiate several es_role resources).

```
profile::elasticsearch::es_roles:
  'advanced':
    privileges:
      cluster: ['monitor']
      indices:
        - names: ['advancedindex']
          privileges: ['read']
          field_security:
            grant: ['field_a', 'field_a*', 'field_b']
            except: ['field_d']
          query: '{ "match" : { "field_a" : "token" } }'
```

Obtaining the roles.yaml

```
advanced:
  cluster:
  - monitor
  indices:
  - field_security:
      except:
      - field_a
      grant:
      - field_a*
      - field_b
    names:
    - advancedindex
    privileges:
    - read
    query: '{ "match" : { "field_a" : "token" } }'
```

Tested, works like a charm.

We can close this :1st_place_medal:
