### ISSUE TITLE
Again issues with init commandline (default.path.home=${ES_HOME})

### ISSUE THREAD

**Issue by guzmanbraso** [elastic/puppet-elasticsearch#873]
* Module version: 5.4.3 (Latest)
* Puppet version: 3.8.7
* OS and version: Debian 7.0
* Elasticsearch 5.6

## Bug description

After seeing this issue reported ( #822 ) and checking I'm with the latest version of the module I really don't know where else to check and why the module still sets my command line as:

> DAEMON_OPTS="-d -p $PID_FILE -Edefault.path.conf=${CONF_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.home=${ES_HOME} -Edefault.path.logs=${LOG_DIR}"

Which results in elasticsearch unable to startup because default.path.home is not a valid parameter...

Any ideas why this bug which should be fixed long time ago still show up ?

**Comment by tylerjl** [comment]
I just tested with the versions you mentioned, and everything seems to work in my test environment:

```
root@debian-7:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
root@debian-7:~# puppet --version
3.8.7
root@debian-7:~# java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
root@debian-7:~# cat test.pp
class { 'elasticsearch':
        manage_repo => true,
        repo_version => '5.x',
}

elasticsearch::instance { 'es-01' : }
root@debian-7:~# curl localhost:9200
{
  "name" : "debian-7-es-01",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "jCOMXjqJQaOoSwopcQ5cTg",
  "version" : {
    "number" : "5.6.0",
    "build_hash" : "781a835",
    "build_date" : "2017-09-07T03:09:58.087Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
root@debian-7:~#
```

Do you have any additional debugging information that might help pinpoint what you're observing?

**Comment by guzmanbraso** [comment]
I'll give it a deeper look this afternoon, so far have been running sed on the init script after each puppet run.
Your test environment it's same as mine, except I'm a little late with java: 1.8.0_91.

My hiera for ES looks like this:
```
elasticsearch::java_install: false
elasticsearch::manage_repo: true
elasticsearch::repo_version: '5.x'
elasticsearch::datadir:
  - '/media/elasticdrive0'
  - '/media/elasticdrive1'
  - '/media/elasticdrive2'
  - '/media/elasticdrive3'
elasticsearch::config:
  cluster.name: 'staging.elk.sys'
  network.host: '0.0.0.0'
  bootstrap.system_call_filter: 'false'
  discovery.zen.ping.unicast.hosts:
    - 192.168.1.10
    - 192.168.1.11
    - 192.168.1.12
  discovery.zen.minimum_master_nodes: '2'
```
