### ISSUE TITLE
6.3.1 introduced a bug in pipeline serialization

### ISSUE THREAD

**Issue by sergii-sakharov** [elastic/puppet-elasticsearch#973]
* Module version: 6.3.1 - broken
* Module version: 6.3.0 - works
* Puppet version: 5.5.3
* OS and version: CentOS 7
Elastic stack version 6.3.x:

Pipeline Hiera config:

```
profiles::elasticsearch::instance::pipelines:
  kibana-logs-pipeline:
    content:
      description: 'kibana logs pipeline'
      processors:
        - rename:
            field: 'error.code'
            target_field: 'error.type'
            ignore_missing: true
```

## Bug description
Above configuration causes following error:
Error: /Stage[main]/Elasticsearch/Elasticsearch::Pipeline[kibana-logs-pipeline]/Elasticsearch_pipeline[kibana-logs-pipeline]: Could not evaluate: Elasticsearch API responded with: [ignore_missing] property isn't a boolean, but of type [java.lang.String]
